name: "test-local"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
    paths: 
      - dist/index.js
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      if: github.repository == "matootie/dokube"
    - uses: ./
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: universe
    - run: kubectl get nodes
