name: "Run locally"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
jobs:
  run:
    runs-on: ${{ matrix.os }}
    if: ${{ always() }}
    strategy:
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          - windows-2016
          - windows-2019
    steps:
    - uses: actions/checkout@v1
      if: github.repository == 'matootie/dokube'
    - uses: ./
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: yoiksoft
        expirationTime: 90
        namespace: default
        version: 1.17.4
    - run: kubectl get nodes
    - run: kubectl top nodes
