name: "Run locally"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      if: github.repository == 'matootie/dokube'
    - uses: ./
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: yoiksoft
        expirationTime: 90
        namespace: default
        version: 1.17.4
    - run: kubectl get nodes
